EXP-23 Edit expense + validations and add expense touchups
EndavaCollab/be_expenses_manager pull request #11
Opened 2023-10-02 17:02 UTC by zsoltibv

2023-10-02 17:54 UTC, FitaRoberttt commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +        Optional<Expense> existingExpense = expenseRepository.findById(expenseId);
I think you can simplify here by using `expenseRepository.findById(expenseId).orElseThrow()`. This eliminates the need for the `if` condition and `Optional`.

2023-10-02 17:54 UTC, FitaRoberttt approved these changes

2023-10-05 07:02 UTC, en-dragos-dordea requested changes

2023-10-09 07:13 UTC, en-dragos-dordea requested changes

2023-10-09 07:13 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +    public ResponseEntity<ExpenseDto> addExpense(@RequestBody @Valid ExpenseDto expenseDto) throws RuntimeException {
No need to specify that the method throws `RuntimeException`, as this kind of exception is unchecked. Please remove the throws from methods signatures

2023-10-09 07:13 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/exception/handler/ApiExceptionHandler.java
> +    }
These exceptions can be handled in the same method - `@ExceptionHandler` can take an array

2023-10-09 07:13 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/mapper/ExpenseMapper.java
> +            throws ExpenseNotFoundException, UserNotFoundException, CategoryNotFoundException, CurrencyNotFoundException {
The throws can be removed from here too

2023-10-10 08:23 UTC, en-dragos-dordea approved these changes

2023-10-10 08:24 UTC, merged