Exp 23 change currency
EndavaCollab/be_expenses_manager pull request #12
Opened 2023-10-05 09:19 UTC by StefanFrusi

2023-10-06 08:55 UTC, zsoltibv requested changes

2023-10-06 08:55 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +    public List<Expense> getExpensesByDates(LocalDate beginDate, LocalDate endDate, Integer userId) {
this method only calls one method, move impelementation to this method

2023-10-06 08:55 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/repository/ExpenseRepository.java
> +    List<Expense> findExpensesBetweenDatesForUser(
you are querying for LocalDate but in db you have LocalDateTime, for me it throws IllegalArgumentException exception.

it works if i change to: 
@Query("SELECT e FROM Expense e WHERE CAST(e.expenseDate AS DATE) BETWEEN :startDate AND :endDate AND e.user.userId = :userId")

2023-10-10 10:07 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +        for (int i = 0; i < expenses.size(); i++) {
This logic should stay in a service, add a new service TotalService where you can use the CurrencyService and EspensesService to build up your logic, beside this we need to have a new controller for Total.

Move this endpoint in a TotalController.

2023-10-10 10:08 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +    public ResponseEntity<?> getTotalSumCategory(@RequestParam int userId, @RequestParam LocalDate startDate, @RequestParam LocalDate endDate, @RequestParam String code) {
return type missing. This endpoint should stay in TotalController.

2023-10-10 10:09 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +            return new ResponseEntity<>("The end date is invalid", HttpStatus.BAD_REQUEST);
throw an error, catch that error in ApiExceptionHandler and return from there a BAD_REQUEST.

@ExceptionHandler(IllegalArgumentException.class) as an example on how to catch it.

2023-10-10 10:10 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +        Map<String, BigDecimal> resultMap = expenseService.sortExpenses(expenses);
Move logic from controller to service layer.

2023-10-10 10:11 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +    public ResponseEntity<?> getCurrencies() {
We need a new currencies controller.

2023-10-10 10:12 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/CurrencyService.java
> +     List<Currency> getCurrencies();
Service should return Dto not the entity.

2023-10-10 10:12 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/ExpenseService.java
> +    List<Expense> getExpensesByDates(LocalDate beginDate, LocalDate endDate, Integer userId);
Service should return Dto not the entity.

2023-10-10 10:14 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +        return expenseRepository.findExpensesBetweenDatesForUser(beginDate.atStartOfDay(), endDate.atStartOfDay(), userId);
Return Dto, not Entity

2023-10-10 10:14 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +    public List<Expense> getExpensesByDates(LocalDate beginDate, LocalDate endDate, Integer userId) {
Return Dto, not Entity

2023-10-10 10:21 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/impl/CurrencyServiceImpl.java
> +        for (int i = 0; i < expenseList.size(); i++) {
Use enhance for. It is hard to read the  code as it is, IntelliJ gives some hints regarding the code, check them out.

2023-10-24 09:44 UTC, en-alex-trunchi requested changes
I didn't have time to check the logic from here CurrencyServiceImpl. @en-dragos-dordea @en-ciprian-parvan do you have some time to check it?

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +import com.endava.expensesmanager.service.CurrencyService;
remove unused imports

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +
remove extra line

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +
remove extra line

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +
remove extra line

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +
remove extra line

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +import org.springframework.web.bind.annotation.RestController;
remove unused imports

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +    public ResponseEntity<?> getTotalSum(@RequestParam int userId, @RequestParam LocalDateTime startDate, @RequestParam LocalDateTime endDate, @RequestParam String code) {
add return type, don't use "?"

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +            return new ResponseEntity<>("The end date is invalid", HttpStatus.BAD_REQUEST);
We can throw IllegalArgumentException in here, make sure that this Exception returns 400 Bad_Request from ApiExceptionHandler

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +
delete extra lines

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/impl/TotalServiceImpl.java
> +
delete extra lines

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/impl/TotalServiceImpl.java
> +
delete extra lines

2023-10-24 09:44 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/impl/CurrencyServiceImpl.java
> +
delete extra lines

2023-10-24 19:42 UTC, FitaRoberttt approved these changes

2023-10-26 14:17 UTC, merged