Exp 24 delete expense
EndavaCollab/be_expenses_manager pull request #13
Opened 2023-10-05 14:09 UTC by StefanFrusi

2023-10-08 20:55 UTC, FitaRoberttt approved these changes

2023-10-10 10:40 UTC, en-alex-trunchi requested changes

2023-10-10 10:40 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +    public ResponseEntity<?> deleteExpenseById(@RequestParam Integer expenseId)
The Controller already has /expense path, just {expenseId} should be enough

2023-10-10 10:40 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/ExpenseService.java
> +        ResponseEntity<?> deleteExpenseById(Integer expenseId);
For delete we have void return type.

2023-10-10 10:40 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +        return new ResponseEntity<>("The expense does not exist",HttpStatus.NOT_FOUND);
throw an error like NotFoundException and catch that in ApiExceptionHandler where you can return not found status.

2023-10-23 07:59 UTC, en-dragos-dordea commented on pom.xml
> +		</dependency>
Lombok is already imported (line 42-46) - can we remove these extra dependencies?

2023-10-24 14:32 UTC, en-alex-trunchi approved these changes

2023-10-27 06:57 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +        throw new ExpenseNotFoundException(expenseId);
This will throw the exception in all cases. We should return after deleting it.

2023-10-27 16:51 UTC, en-dragos-dordea requested changes

2023-10-27 16:51 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +
please remove empty line

2023-10-27 16:51 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +
please remove empty line

2023-10-27 16:51 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +
please remove empty lines

2023-10-27 16:51 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/ExpenseService.java
> +        void seedExpenses(Integer nrOfExpenses, Integer nrOfDays);//
why are there '//' at the end?

2023-10-27 16:51 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +    @DeleteMapping("{expenseId}")
this should be `{expenseId}`

2023-10-30 17:07 UTC, zsoltibv commented
Tested file deletion on azure account and working.

2023-10-31 07:59 UTC, en-dragos-dordea requested changes

2023-10-31 07:59 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +            expenseOptional.ifPresent(expense -> {
We already know that the `expenseOptional` is present here, so this `ifPresent` check is not needed

2023-10-31 08:05 UTC, merged