EXP-48 Add Expense Document
EndavaCollab/be_expenses_manager pull request #15
Opened 2023-10-10 19:42 UTC by zsoltibv

2023-10-11 13:06 UTC, en-ciprian-parvan requested changes

2023-10-11 13:28 UTC, en-ciprian-parvan commented
There's something that I think it's worth mentioning. In this PR there's an addition in the `schema.sql` of `document_id` column to `expenses` table. If you have the database and table already created, the new column won't be added when you run the BE service. You need to execute `DROP TABLE expenses`***** command before and then to run the service.

*****Make sure to create a SQL dump before, if you have data you don't want to lose.

2023-10-16 00:37 UTC, FitaRoberttt approved these changes

2023-10-17 19:56 UTC, zsoltibv commented
Implemented saving of uploaded document images to Azure Storage Account Container. Tested and working on my Azure account (with my connection string).

2023-10-27 06:50 UTC, en-ciprian-parvan commented on src/main/resources/application.properties
> +<<<<<<< HEAD
Can you remove the unnecessary lines like this one?

2023-10-27 06:50 UTC, en-ciprian-parvan commented on src/main/resources/application.properties
> +document.upload.directory=src/main/resources/documents
Is this needed anymore?

2023-10-27 06:50 UTC, en-ciprian-parvan commented on src/main/resources/application.properties
> +azure.document.blob.accountKey=OtTH289PzMAJHwMtZRM1dDHEzXrJ62nnwnc8PKuzZdC4vVhjoXBcnEUA8befM1O3/F2IMtS1lj+y+AStZPSL8Q==
If this is your Azure account, can you reach to DevOps team to give you the one that they created and it will be used? If everything is in place, update all the needed properties.

2023-10-27 08:27 UTC, en-ciprian-parvan approved these changes

2023-10-27 08:27 UTC, merged