EXP-61 Database Seeder for Expenses (200 expenses)
EndavaCollab/be_expenses_manager pull request #16
Opened 2023-10-16 00:26 UTC by zsoltibv

2023-10-16 00:37 UTC, FitaRoberttt approved these changes

2023-10-17 07:39 UTC, en-ciprian-parvan requested changes

2023-10-17 07:39 UTC, en-ciprian-parvan commented on src/main/java/com/endava/expensesmanager/seeder/ExpenseSeeder.java
> +        for (int i = 0; i < 200; i++) {
The number of expenses to be inserted in the table can be retrieved from a parameter passed in URL. Also, consider a default value for how many rows to be inserted (for e.g. 200): this will be used if the URL parameter does not have a value or if there is a value greater than 2000.

2023-10-17 07:39 UTC, en-ciprian-parvan commented on src/main/java/com/endava/expensesmanager/seeder/ExpenseSeeder.java
> +        expenseDto.setExpenseDate(LocalDateTime.now().minusDays(ThreadLocalRandom.current().nextInt(1, 90)));
You can get from a URL parameter the value for many days before the current date an expense can have its date. You can have 90 as a default value to be used when there is no value passed in the URL parameter or if the value is greater than 540.

2023-10-17 10:50 UTC, en-ciprian-parvan requested changes

2023-10-17 10:50 UTC, en-ciprian-parvan commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +            Expense fakeExpense = ExpenseGenerator.generateFakeExpense(nrOfDays);
Just one more thing. You can define a list and store in it all the generated expenses. After the for loop is over you can use `.saveAll(list)` method (it's faster than `save()` method) to insert the expenses into database.

2023-10-18 06:59 UTC, merged