EXP-9 user model login/create endpoint
EndavaCollab/be_expenses_manager pull request #6
Opened 2023-09-19 07:58 UTC by FitaRoberttt

2023-09-19 08:36 UTC, zsoltibv requested changes

2023-09-19 08:36 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/controller/UserController.java
> +        @PostMapping("/loginOrCreate/{name}")
here should be /auth/{name} according to swagger documentation

2023-09-19 08:36 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/controller/UserController.java
> +            return new ResponseEntity<>("User with name " + name + " was not found in our list", HttpStatus.NOT_ACCEPTABLE);
here you could use HttpStatus.NOT_FOUND instead

2023-09-19 08:36 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/service/impl/UserServiceImpl.java
> +        public Optional<User> removeUser(String name) {
use user id to delete instead of name

2023-09-19 08:58 UTC, en-dragos-dordea requested changes

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/UserController.java
> +//        }
We should remove unused commented code

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/UserController.java
> +        @DeleteMapping("/delete/{name}")
The delete functionality is not required in this task, can we remove it please?

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/User.java
> +    private Date createdAt;
The type in DB is `DATETIME`, we need a type here that stores also the time. Lets use the java 8 `LocalDateTime`

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/User.java
> +    private Integer user_id;
Lets use the camel-case naming convention for `user_id` too

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/UserController.java
> +            return new ResponseEntity<>(user, HttpStatus.OK);
We should return the `User` object, not an `Optional`.

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/UserService.java
> +//    void addUser(User user);
Can we remove unused commented code please?

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/UserService.java
> +    Optional<User> removeUser(String name);
Delete is not needed, can we remove it?

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/UserService.java
> +    Optional<User> getOrCreateUserByName(String name);
This can return a `User` object, because inside the method, we either get the user or create it, so we are certain that a valid user is returned here.

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/UserServiceImpl.java
> +//        }
Can we remove unused commented code please?

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/UserServiceImpl.java
> +                return Optional.of(newUser);
We can simply return `existingUser.get()` or `newUser` here, so that `Optional` is not needed further.

2023-09-19 08:58 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/UserServiceImpl.java
> +        public Optional<User> removeUser(String name) {
Delete is not needed, can we remove it please?

2023-09-19 14:05 UTC, zsoltibv approved these changes

2023-09-20 05:23 UTC, en-alex-trunchi requested changes

2023-09-20 05:23 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/service/UserService.java
> +    User getOrCreateUserByName(String name);
We should not return the User entity from the UserService, create an UserDto. Split them into two folders entity and dto. 
Create a mapper class where to map the entity to dto and dto to entity. you can have the mapper folder inside the model. The mapper class can have static methods

2023-09-20 06:20 UTC, en-dragos-dordea requested changes

2023-09-20 06:20 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/UserService.java
> +    User getOrCreateUserByName(String name);
The `createdAt` field is not needed in the frontend, so we can exclude it from the `UserDto` objects.

2023-09-20 06:20 UTC, en-dragos-dordea commented on src/main/resources/application.properties
> +spring.sql.init.schema-locations=classpath:database_dump/mydb_dump.sql
These changes are on the main branch. You can do a rebase with main branch on your branch to get the latest changes. Let me know if you need a hand on that.

2023-09-20 08:14 UTC, FitaRoberttt commented on src/main/resources/application.properties
> +spring.sql.init.schema-locations=classpath:database_dump/mydb_dump.sql
> These changes are on the main branch. You can do a rebase with main branch on your branch to get the latest changes. Let me know if you need a hand on that.

I would need some help with. Let me know when you can.

2023-09-20 13:37 UTC, en-alex-trunchi requested changes

2023-09-20 13:37 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/model/mapper/UserMapper.java
> +    public static UserDto userToUserDto(User user)
could be simplified to mapToDto

2023-09-20 13:37 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/model/mapper/UserMapper.java
> +    public static User userDtoToUser(UserDto userDto)
mapToEntity

2023-09-20 13:37 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/UserController.java
> +            UserDto userDto = UserMapper.userToUserDto(user);
All good, but this mapping should be done at a service layer (UserService)

2023-09-20 13:37 UTC, en-alex-trunchi commented on src/main/java/com/endava/expensesmanager/controller/UserController.java
> +import com.endava.expensesmanager.model.entity.User;
remove import of entity user

2023-09-20 14:11 UTC, en-alex-trunchi approved these changes

2023-09-21 06:28 UTC, en-dragos-dordea approved these changes

2023-09-21 06:28 UTC, merged