Exp 12 data fetch
EndavaCollab/be_expenses_manager pull request #7
Opened 2023-09-22 06:20 UTC by StefanFrusi

2023-09-25 08:25 UTC, zsoltibv requested changes

2023-09-25 08:25 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +        for(int i=0;i<=expenses.size();i++)
index out of bounds error here, should be "<" instead of "<=", you're exceeding list size

2023-09-25 08:25 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/model/entity/Category.java
> +    @OneToMany(mappedBy = "category_id" )
mapping error, category_id field doesn't exist in Expense entity. Use "category" instead

2023-09-25 08:25 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/model/entity/Currency.java
> +    @OneToMany(mappedBy = "currency_id" )
mapping error, currency_id field doesn't exist in Expense entity. Use "currency" instead

2023-09-25 08:25 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/repository/ExpenseRepository.java
> +    @Query("SELECT e FROM Expense e WHERE e.expenseDate BETWEEN :startDate AND :endDate AND e.user.userId = :userId")
maybe make this end date inclusive

2023-09-25 08:25 UTC, zsoltibv commented on src/main/java/com/endava/expensesmanager/service/impl/CategoryLogicImpl.java
> +public class CategoryLogicImpl implements CategoryLogic {
maybe move this class to a helper/utils package

2023-09-25 11:46 UTC, en-dragos-dordea requested changes

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +    CategoryServiceImpl categoryService;
This should also be injected in constructor/setter.

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +        for(int i=0;i<=expenses.size();i++)
Lets better create the sum using streams - `reduce` method.

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +        }
This logic should be in a service class.

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +    public ResponseEntity<?> getTotalSum(@RequestParam int userId, @RequestParam LocalDate startDate, @RequestParam LocalDate endDate)
Can we do some validations on the date params? Also the `userId` should be of type `Integer`, otherwise the default value will be 0.

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +    public ResponseEntity<?> getTotalSumCategory(@RequestParam int userId, @RequestParam LocalDate startDate, @RequestParam LocalDate endDate)
Same here, lets change the `userId` type to `Integer`

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +// ADD NEW QUERY without START END AND END DATE
Can we remove these comments please?

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/controller/TotalController.java
> +        Map<Integer, BigDecimal> resultMap = categoryLogic.sortExpenses(expenses,categories);
Can we move this logic to a separate class? And only call one method that returns the final map result.

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/entity/Category.java
> +    private int categoryId;
Lets make the ids object types - in this case `Integer`

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/entity/Currency.java
> +    private int currencyId;
Lets make this `Integer`

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/entity/Currency.java
> +    private List<Expense> expenses;
Do we need a list of expenses here?

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/entity/Expense.java
> +    private int expenseId;
Lets change this to `Integer`

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/CategoryLogicImpl.java
> +            .anyMatch(category -> category.getCategoryId() == expense.getCategory().getCategoryId()))
Why filtering and checking if any match here? Also, do we need the categories list?

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/CategoryServiceImpl.java
> +    private CategoryRepository categoryRepository;
Lets autowire this dependency via constructor/setter

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +    ExpenseRepository expenseRepository;
Lets autowire this dependency via constructor/setter

2023-09-25 11:46 UTC, en-dragos-dordea commented on src/main/java/com/endava/expensesmanager/model/entity/Category.java
> +    private List<Expense> expenses;
Do we need a list of expenses here?

2023-10-05 07:15 UTC, en-dragos-dordea commented
Will be merged in another PR

2023-10-05 07:15 UTC, closed without merging